name: lrc
description: A Dart-only package that creates, parses, and handles LRC, which is a format that stores song lyrics.
version: 1.0.2
repository: https://github.com/Yivan000/lrc

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
